server:
  # 端口号
  port: 80
management:
  endpoints:
    web:
      exposure:
        # 开启所有 WEB 端点暴露
        include: "*"
spring:
  application:
    # 服务名称
    name: gateway
  cloud:
    nacos:
      # Nacos 地址
      server-addr: 49.235.75.117:8848
    gateway:
      discovery:
        locator:
          # 开启根据服务名动态获取路由地址
          enabled: true
      # 路由配置
      routes:
        # 路由唯一标识
        - id: user_route
          # lb 表明后台服务转发使用负载均衡 lb://服务名
          uri: lb://user-server
          # 访问路径
          predicates:
            - Path=/user/**
        - id: product_route
          uri: lb://product-server
          predicates:
            - Path=/product/**
        - id: order_route
          uri: lb://order-server
          predicates:
            - Path=/order/**
        - id: file_route
          uri: lb://file-server
          predicates:
            - Path=/file/**
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://zhno.xyz:3306/shop?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 3320
 # 自定义需要认证列表
list:
  items:
    - "test"